# -*- coding: utf-8 -*-
"""CourseWork-prefinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aD6mT-NBBgiOpKOlwH5ikdXhMEburcov
"""

# ----------------------------------------------------------
# app.py — Streamlit Dashboard for Weather Data (Enhanced)
# ----------------------------------------------------------

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import matplotlib.pyplot as plt
from datetime import datetime, timedelta

# ML libraries
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, DBSCAN
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import silhouette_score, r2_score, mean_absolute_error
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

pip install statsmodels

# Time series
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

st.set_page_config(
    page_title="Weather Analytics Dashboard",
    layout="wide",
    page_icon="🌤️"
)

# ----------------------------------------------------------
# LOAD DATA
# ----------------------------------------------------------
@st.cache_data
def load_data():
    countries_weather_df = pd.read_csv("countries.csv")
    cities_weather_df = pd.read_csv("cities.csv")
    daily_weather_df = pd.read_csv("daily_weather_smallest.csv")
    return countries_weather_df, cities_weather_df, daily_weather_df

countries_weather_df, cities_weather_df, daily_weather_df = load_data()

# ----------------------------------------------------------
# DATA PREPROCESSING
# ----------------------------------------------------------
def preprocess_data(df_list, names):
    processed = []
    for df, name in zip(df_list, names):
        df_clean = df.copy()
        df_clean.drop_duplicates(inplace=True)

        # Store info about missing values before dropping
        missing_info = df_clean.isnull().sum()

        # For daily weather, we might want to fill some missing values
        if name == 'daily':
            numeric_cols = df_clean.select_dtypes(include=[np.number]).columns
            df_clean[numeric_cols] = df_clean[numeric_cols].fillna(df_clean[numeric_cols].mean())
            # Convert date if exists
            if 'date' in df_clean.columns:
                df_clean['date'] = pd.to_datetime(df_clean['date'])
                df_clean['year'] = df_clean['date'].dt.year
                df_clean['month'] = df_clean['date'].dt.month
                df_clean['season'] = df_clean['month'] % 12 // 3 + 1
                season_map = {1: 'Winter', 2: 'Spring', 3: 'Summer', 4: 'Fall'}
                df_clean['season_name'] = df_clean['season'].map(season_map)

        processed.append(df_clean)
    return processed

countries_weather_df, cities_weather_df, daily_weather_df = preprocess_data(
    [countries_weather_df, cities_weather_df, daily_weather_df],
    ['countries', 'cities', 'daily']
)

# ----------------------------------------------------------
# HELPER FUNCTIONS
# ----------------------------------------------------------
def create_kpi_card(title, value, delta=None, delta_color="normal"):
    """Create a KPI card for dashboard"""
    return {
        'title': title,
        'value': value,
        'delta': delta,
        'delta_color': delta_color
    }

def time_series_decomposition(data, column, period=365):
    """Decompose time series into trend, seasonal, and residual"""
    decomposition = seasonal_decompose(data[column].values, model='additive', period=period)
    return decomposition

# ----------------------------------------------------------
# SIDEBAR
# ----------------------------------------------------------
st.sidebar.title("🌤️ Weather Analytics")
st.sidebar.markdown("---")

# Навигация
page = st.sidebar.radio(
    "Навигация",
    ["📊 Визуализация данных", "🔍 Результаты анализа", "📈 Прогнозирование", "ℹ️ О проекте"]
)

st.sidebar.markdown("---")

# Глобальные фильтры
st.sidebar.header("Глобальные фильтры")

# Датасет для анализа
dataset_choice = st.sidebar.selectbox(
    "Основной датасет:",
    ["Daily Weather", "Cities", "Countries"]
)

# Временной фильтр (если есть даты)
if dataset_choice == "Daily Weather" and 'date' in daily_weather_df.columns:
    min_date = daily_weather_df['date'].min()
    max_date = daily_weather_df['date'].max()
    date_range = st.sidebar.date_input(
        "Диапазон дат:",
        [min_date, max_date]
    )

st.sidebar.markdown("---")
st.sidebar.info("""
**Инструкция:**
1. Выберите страницу навигации
2. Используйте фильтры для настройки
3. Взаимодействуйте с графиками
""")

# ==========================================================
# PAGE 1 — RAW DATA VISUALIZATION (ENHANCED)
# ==========================================================
if page == "📊 Визуализация данных":

    # Header
    col1, col2 = st.columns([3, 1])
    with col1:
        st.title("📊 Визуализация исходных данных")
    with col2:
        st.metric("Всего записей", f"{len(daily_weather_df):,}")

    # KPI Cards
    st.subheader("📈 Ключевые показатели")

    # Выбор датасета для отображения KPI
    kpi_dataset = st.selectbox("Датасет для KPI:", ["Daily Weather", "Cities", "Countries"])

    if kpi_dataset == "Daily Weather":
        df_kpi = daily_weather_df
        col1, col2, col3, col4 = st.columns(4)
        with col1:
            st.metric("Города", df_kpi['city_name'].nunique() if 'city_name' in df_kpi.columns else "N/A")
        with col2:
            st.metric("Диапазон дат",
                     f"{df_kpi['date'].min().date() if 'date' in df_kpi.columns else 'N/A'} - "
                     f"{df_kpi['date'].max().date() if 'date' in df_kpi.columns else 'N/A'}")
        with col3:
            numeric_cols = df_kpi.select_dtypes(include=[np.number]).columns
            st.metric("Числовых признаков", len(numeric_cols))
        with col4:
            st.metric("Пропущенных значений", df_kpi.isnull().sum().sum())

    # Tabs for different visualizations
    tab1, tab2, tab3, tab4 = st.tabs([
        "📋 Данные и статистика",
        "📊 Распределения",
        "🔗 Корреляции",
        "🌍 Геоданные"
    ])

    with tab1:
        st.header("Данные и описательная статистика")

        # Выбор датасета для таблицы
        dataset_for_table = st.selectbox("Датасет:", ["Daily Weather", "Cities", "Countries"])

        if dataset_for_table == "Daily Weather":
            df_table = daily_weather_df
        elif dataset_for_table == "Cities":
            df_table = cities_weather_df
        else:
            df_table = countries_weather_df

        # Поиск и фильтрация
        col1, col2 = st.columns(2)
        with col1:
            search_term = st.text_input("🔍 Поиск по таблице:", "")
        with col2:
            items_per_page = st.slider("Записей на страницу:", 10, 100, 20)

        # Применение поиска
        if search_term:
            df_display = df_table[df_table.apply(
                lambda row: row.astype(str).str.contains(search_term, case=False).any(),
                axis=1
            )]
        else:
            df_display = df_table

        # Пагинация
        total_pages = max(1, len(df_display) // items_per_page)
        page_num = st.number_input("Страница:", 1, total_pages, 1)

        start_idx = (page_num - 1) * items_per_page
        end_idx = min(start_idx + items_per_page, len(df_display))

        # Отображение таблицы
        st.dataframe(
            df_display.iloc[start_idx:end_idx],
            use_container_width=True,
            height=400
        )

        st.caption(f"Показано {start_idx+1}-{end_idx} из {len(df_display)} записей")

        # Статистика
        st.subheader("📊 Статистика")
        numeric_cols_table = df_table.select_dtypes(include=[np.number]).columns
        if len(numeric_cols_table) > 0:
            st.dataframe(df_table[numeric_cols_table].describe())

        # Missing values
        st.subheader("🔍 Пропущенные значения")
        missing_df = pd.DataFrame({
            'Колонка': df_table.columns,
            'Пропуски': df_table.isnull().sum().values,
            '% пропусков': (df_table.isnull().sum().values / len(df_table) * 100).round(2)
        })
        st.dataframe(missing_df[missing_df['Пропуски'] > 0])

    with tab2:
        st.header("Распределения признаков")

        dataset_for_dist = st.selectbox("Датасет для анализа распределений:",
                                       ["Daily Weather", "Cities", "Countries"])

        if dataset_for_dist == "Daily Weather":
            df_dist = daily_weather_df
            num_cols = df_dist.select_dtypes(include=[np.number]).columns
            cat_cols = df_dist.select_dtypes(exclude=[np.number]).columns
        elif dataset_for_dist == "Cities":
            df_dist = cities_weather_df
            num_cols = df_dist.select_dtypes(include=[np.number]).columns
            cat_cols = df_dist.select_dtypes(exclude=[np.number]).columns
        else:
            df_dist = countries_weather_df
            num_cols = df_dist.select_dtypes(include=[np.number]).columns
            cat_cols = df_dist.select_dtypes(exclude=[np.number]).columns

        # Выбор типа визуализации
        viz_type = st.radio(
            "Тип визуализации:",
            ["Гистограмма", "Box Plot", "Violin Plot", "Density Plot", "Bar Chart"]
        )

        if viz_type in ["Гистограмма", "Box Plot", "Violin Plot", "Density Plot"]:
            col_selected = st.selectbox("Выберите числовой признак:", num_cols)

            if viz_type == "Гистограмма":
                fig = px.histogram(df_dist, x=col_selected, nbins=50,
                                  title=f"Распределение {col_selected}")
            elif viz_type == "Box Plot":
                fig = px.box(df_dist, y=col_selected, title=f"Box Plot {col_selected}")
            elif viz_type == "Violin Plot":
                fig = px.violin(df_dist, y=col_selected, title=f"Violin Plot {col_selected}")
            else:  # Density Plot
                fig = px.density_contour(df_dist, x=col_selected,
                                        title=f"Плотность распределения {col_selected}")

            st.plotly_chart(fig, use_container_width=True)

            # Дополнительная статистика
            col1, col2, col3, col4 = st.columns(4)
            with col1:
                st.metric("Среднее", f"{df_dist[col_selected].mean():.2f}")
            with col2:
                st.metric("Медиана", f"{df_dist[col_selected].median():.2f}")
            with col3:
                st.metric("Стд. отклонение", f"{df_dist[col_selected].std():.2f}")
            with col4:
                st.metric("Асимметрия", f"{df_dist[col_selected].skew():.2f}")

        else:  # Bar Chart для категориальных
            if len(cat_cols) > 0:
                cat_selected = st.selectbox("Выберите категориальный признак:", cat_cols)
                top_n = st.slider("Количество категорий для отображения:", 5, 50, 10)

                counts = df_dist[cat_selected].value_counts().head(top_n).reset_index()
                counts.columns = [cat_selected, 'count']

                fig = px.bar(counts, x=cat_selected, y='count',
                            title=f"Распределение {cat_selected} (топ-{top_n})")
                st.plotly_chart(fig, use_container_width=True)

    with tab3:
        st.header("Корреляционный анализ")

        dataset_for_corr = st.selectbox("Датасет для корреляций:",
                                       ["Daily Weather", "Cities", "Countries"])

        if dataset_for_corr == "Daily Weather":
            df_corr = daily_weather_df
        elif dataset_for_corr == "Cities":
            df_corr = cities_weather_df
        else:
            df_corr = countries_weather_df

        numeric_cols_corr = df_corr.select_dtypes(include=[np.number]).columns

        if len(numeric_cols_corr) > 1:
            # Heatmap
            corr_matrix = df_corr[numeric_cols_corr].corr()

            fig = px.imshow(corr_matrix,
                           text_auto=True,
                           aspect="auto",
                           title="Корреляционная матрица",
                           color_continuous_scale='RdBu_r')
            st.plotly_chart(fig, use_container_width=True)

            # Scatter matrix
            st.subheader("Матрица рассеяния")
            selected_cols = st.multiselect(
                "Выберите признаки для матрицы рассеяния:",
                numeric_cols_corr.tolist(),
                default=numeric_cols_corr[:4].tolist()
            )

            if len(selected_cols) >= 2:
                fig = px.scatter_matrix(df_corr[selected_cols])
                st.plotly_chart(fig, use_container_width=True)

            # Top correlations
            st.subheader("Наиболее значимые корреляции")
            corr_pairs = []
            for i in range(len(corr_matrix.columns)):
                for j in range(i+1, len(corr_matrix.columns)):
                    corr_pairs.append({
                        'Признак 1': corr_matrix.columns[i],
                        'Признак 2': corr_matrix.columns[j],
                        'Корреляция': corr_matrix.iloc[i, j]
                    })

            corr_df = pd.DataFrame(corr_pairs)
            corr_df['abs_corr'] = corr_df['Корреляция'].abs()

            top_n_corr = st.slider("Количество топ-корреляций:", 5, 50, 10)
            top_corr = corr_df.nlargest(top_n_corr, 'abs_corr')

            st.dataframe(top_corr[['Признак 1', 'Признак 2', 'Корреляция']])

    with tab4:
        st.header("Географическая визуализация")

        if 'latitude' in cities_weather_df.columns and 'longitude' in cities_weather_df.columns:

            # Выбор признака для цветового кодирования
            numeric_cols_geo = cities_weather_df.select_dtypes(include=[np.number]).columns

            color_by = st.selectbox(
                "Цветовое кодирование по:",
                ['None'] + numeric_cols_geo.tolist()
            )

            size_by = st.selectbox(
                "Размер точек по:",
                ['None'] + numeric_cols_geo.tolist()
            )

            # Фильтр по значениям
            if color_by != 'None':
                min_val, max_val = st.slider(
                    f"Диапазон для {color_by}:",
                    float(cities_weather_df[color_by].min()),
                    float(cities_weather_df[color_by].max()),
                    (float(cities_weather_df[color_by].min()),
                     float(cities_weather_df[color_by].max()))
                )
                df_geo = cities_weather_df[
                    (cities_weather_df[color_by] >= min_val) &
                    (cities_weather_df[color_by] <= max_val)
                ]
            else:
                df_geo = cities_weather_df

            # Создание карты
            fig = px.scatter_geo(df_geo,
                                lat='latitude',
                                lon='longitude',
                                color=color_by if color_by != 'None' else None,
                                size=size_by if size_by != 'None' else None,
                                hover_name='city_name' if 'city_name' in df_geo.columns else None,
                                title='Распределение городов',
                                projection='natural earth')

            st.plotly_chart(fig, use_container_width=True)

# ==========================================================
# PAGE 2 — ANALYSIS RESULTS (ENHANCED)
# ==========================================================
elif page == "🔍 Результаты анализа":

    st.title("🔍 Результаты анализа данных")

    # Выбор метода анализа
    analysis_method = st.selectbox(
        "Метод анализа:",
        ["Кластеризация", "Регрессия", "Анализ временных рядов", "PCA - Анализ главных компонент"]
    )

    # Общие настройки
    st.sidebar.header("Настройки анализа")

    # Выбор датасета
    if analysis_method in ["Кластеризация", "Регрессия", "PCA - Анализ главных компонент"]:
        analysis_dataset = st.sidebar.selectbox(
            "Датасет для анализа:",
            ["Daily Weather", "Cities", "Countries"]
        )
    else:
        analysis_dataset = "Daily Weather"

    if analysis_dataset == "Daily Weather":
        df_analysis = daily_weather_df
        df_norm = daily_weather_df.copy()
        scaler = StandardScaler()
        numeric_cols = df_analysis.select_dtypes(include=[np.number]).columns
        df_norm[numeric_cols] = scaler.fit_transform(df_analysis[numeric_cols])
    elif analysis_dataset == "Cities":
        df_analysis = cities_weather_df
        df_norm = cities_weather_df.copy()
        scaler = StandardScaler()
        numeric_cols = df_analysis.select_dtypes(include=[np.number]).columns
        df_norm[numeric_cols] = scaler.fit_transform(df_analysis[numeric_cols])
    else:
        df_analysis = countries_weather_df
        df_norm = countries_weather_df.copy()
        scaler = StandardScaler()
        numeric_cols = df_analysis.select_dtypes(include=[np.number]).columns
        df_norm[numeric_cols] = scaler.fit_transform(df_analysis[numeric_cols])

    # ========== КЛАСТЕРИЗАЦИЯ ==========
    if analysis_method == "Кластеризация":
        st.header("Кластеризация данных")

        col1, col2 = st.columns(2)

        with col1:
            # Выбор алгоритма
            cluster_algo = st.selectbox(
                "Алгоритм кластеризации:",
                ["K-Means", "DBSCAN"]
            )

            # Выбор признаков
            features = st.multiselect(
                "Признаки для кластеризации:",
                numeric_cols.tolist(),
                default=numeric_cols[:2].tolist() if len(numeric_cols) >= 2 else []
            )

        with col2:
            if cluster_algo == "K-Means":
                n_clusters = st.slider("Количество кластеров:", 2, 10, 3)
                n_init = st.slider("Количество инициализаций:", 1, 20, 10)
            else:  # DBSCAN
                eps = st.slider("EPS (радиус):", 0.1, 5.0, 0.5, 0.1)
                min_samples = st.slider("Минимум образцов:", 1, 20, 5)

        if len(features) >= 2:
            X = df_norm[features].dropna()

            if cluster_algo == "K-Means":
                # K-Means
                kmeans = KMeans(n_clusters=n_clusters, n_init=n_init, random_state=42)
                clusters = kmeans.fit_predict(X)
                centers = kmeans.cluster_centers_

                # Метрики
                inertia = kmeans.inertia_
                silhouette = silhouette_score(X, clusters)

                # Отображение метрик
                col1, col2, col3 = st.columns(3)
                with col1:
                    st.metric("Inertia", f"{inertia:.2f}")
                with col2:
                    st.metric("Silhouette Score", f"{silhouette:.2f}")
                with col3:
                    st.metric("Кластеров", n_clusters)

            else:  # DBSCAN
                dbscan = DBSCAN(eps=eps, min_samples=min_samples)
                clusters = dbscan.fit_predict(X)
                n_clusters = len(set(clusters)) - (1 if -1 in clusters else 0)

                if n_clusters > 0:
                    try:
                        silhouette = silhouette_score(X, clusters)
                    except:
                        silhouette = "N/A"

                    col1, col2, col3 = st.columns(3)
                    with col1:
                        st.metric("Кластеров", n_clusters)
                    with col2:
                        noise_points = sum(clusters == -1)
                        st.metric("Шумовых точек", noise_points)
                    with col3:
                        if silhouette != "N/A":
                            st.metric("Silhouette Score", f"{silhouette:.2f}")

            # Визуализация
            df_viz = df_analysis.loc[X.index].copy()
            df_viz['Cluster'] = clusters

            # 2D визуализация
            if len(features) >= 2:
                fig = px.scatter(
                    df_viz,
                    x=features[0],
                    y=features[1],
                    color='Cluster',
                    title=f"Кластеризация {features[0]} vs {features[1]}",
                    hover_data=df_viz.columns.tolist()
                )

                if cluster_algo == "K-Means":
                    # Добавление центроидов
                    centers_original = scaler.inverse_transform(centers)
                    fig.add_trace(
                        go.Scatter(
                            x=centers_original[:, features.index(features[0])],
                            y=centers_original[:, features.index(features[1])],
                            mode='markers',
                            marker=dict(
                                symbol='x',
                                size=15,
                                color='black',
                                line=dict(width=2)
                            ),
                            name='Центроиды'
                        )
                    )

                st.plotly_chart(fig, use_container_width=True)

            # 3D визуализация (если выбрано 3+ признака)
            if len(features) >= 3:
                fig_3d = px.scatter_3d(
                    df_viz,
                    x=features[0],
                    y=features[1],
                    z=features[2],
                    color='Cluster',
                    title=f"3D Кластеризация"
                )
                st.plotly_chart(fig_3d, use_container_width=True)

            # Анализ кластеров
            st.subheader("📊 Анализ кластеров")

            # Средние значения по кластерам
            cluster_stats = df_viz.groupby('Cluster')[numeric_cols.tolist()].mean()
            st.dataframe(cluster_stats)

            # Количество точек в кластерах
            cluster_counts = df_viz['Cluster'].value_counts().sort_index()
            fig_counts = px.bar(
                x=cluster_counts.index.astype(str),
                y=cluster_counts.values,
                title="Распределение по кластерам",
                labels={'x': 'Кластер', 'y': 'Количество точек'}
            )
            st.plotly_chart(fig_counts, use_container_width=True)

    # ========== РЕГРЕССИЯ ==========
    elif analysis_method == "Регрессия":
        st.header("Регрессионный анализ")

        col1, col2 = st.columns(2)

        with col1:
            # Выбор алгоритма
            reg_algo = st.selectbox(
                "Алгоритм регрессии:",
                ["Linear Regression", "Ridge", "Lasso", "Random Forest", "Gradient Boosting"]
            )

            # Выбор целевой переменной
            target = st.selectbox(
                "Целевая переменная (Y):",
                numeric_cols.tolist()
            )

        with col2:
            # Выбор признаков
            features = st.multiselect(
                "Признаки (X):",
                [col for col in numeric_cols.tolist() if col != target],
                default=[col for col in numeric_cols.tolist() if col != target][:3]
            )

            # Тестовая выборка
            test_size = st.slider("Тестовая выборка (%):", 10, 50, 20) / 100

        if target and len(features) > 0:
            # Подготовка данных
            X = df_norm[features].dropna()
            y = df_norm[target].loc[X.index]

            # Разделение на train/test
            X_train, X_test, y_train, y_test = train_test_split(
                X, y, test_size=test_size, random_state=42
            )

            # Выбор модели
            if reg_algo == "Linear Regression":
                model = LinearRegression()
            elif reg_algo == "Ridge":
                alpha = st.slider("Alpha (Ridge):", 0.01, 10.0, 1.0, 0.01)
                model = Ridge(alpha=alpha)
            elif reg_algo == "Lasso":
                alpha = st.slider("Alpha (Lasso):", 0.01, 10.0, 1.0, 0.01)
                model = Lasso(alpha=alpha)
            elif reg_algo == "Random Forest":
                n_estimators = st.slider("Количество деревьев:", 10, 200, 100)
                model = RandomForestRegressor(n_estimators=n_estimators, random_state=42)
            else:  # Gradient Boosting
                n_estimators = st.slider("Количество деревьев:", 10, 200, 100)
                learning_rate = st.slider("Learning Rate:", 0.01, 0.3, 0.1, 0.01)
                model = GradientBoostingRegressor(
                    n_estimators=n_estimators,
                    learning_rate=learning_rate,
                    random_state=42
                )

            # Обучение модели
            model.fit(X_train, y_train)

            # Прогнозы
            y_pred_train = model.predict(X_train)
            y_pred_test = model.predict(X_test)

            # Метрики
            r2_train = r2_score(y_train, y_pred_train)
            r2_test = r2_score(y_test, y_pred_test)
            mae_train = mean_absolute_error(y_train, y_pred_train)
            mae_test = mean_absolute_error(y_test, y_pred_test)

            # Отображение метрик
            col1, col2, col3, col4 = st.columns(4)
            with col1:
                st.metric("R² Train", f"{r2_train:.3f}")
            with col2:
                st.metric("R² Test", f"{r2_test:.3f}")
            with col3:
                st.metric("MAE Train", f"{mae_train:.3f}")
            with col4:
                st.metric("MAE Test", f"{mae_test:.3f}")

            # Визуализация
            tab1, tab2, tab3 = st.tabs(["📈 Прогнозы", "📊 Важность признаков", "🔍 Остатки"])

            with tab1:
                # Фактические vs предсказанные значения
                fig = go.Figure()

                fig.add_trace(go.Scatter(
                    x=y_test,
                    y=y_pred_test,
                    mode='markers',
                    name='Test данные',
                    marker=dict(color='blue')
                ))

                # Линия идеального прогноза
                min_val = min(y_test.min(), y_pred_test.min())
                max_val = max(y_test.max(), y_pred_test.max())
                fig.add_trace(go.Scatter(
                    x=[min_val, max_val],
                    y=[min_val, max_val],
                    mode='lines',
                    name='Идеальный прогноз',
                    line=dict(color='red', dash='dash')
                ))

                fig.update_layout(
                    title="Фактические vs Предсказанные значения (Test)",
                    xaxis_title="Фактические значения",
                    yaxis_title="Предсказанные значения"
                )

                st.plotly_chart(fig, use_container_width=True)

            with tab2:
                # Важность признаков
                if hasattr(model, 'feature_importances_'):
                    importance_df = pd.DataFrame({
                        'Признак': features,
                        'Важность': model.feature_importances_
                    }).sort_values('Важность', ascending=False)

                    fig = px.bar(
                        importance_df,
                        x='Признак',
                        y='Важность',
                        title="Важность признаков"
                    )
                    st.plotly_chart(fig, use_container_width=True)
                elif hasattr(model, 'coef_'):
                    coef_df = pd.DataFrame({
                        'Признак': features,
                        'Коэффициент': model.coef_
                    }).sort_values('Коэффициент', ascending=False)

                    fig = px.bar(
                        coef_df,
                        x='Признак',
                        y='Коэффициент',
                        title="Коэффициенты модели"
                    )
                    st.plotly_chart(fig, use_container_width=True)

            with tab3:
                # Анализ остатков
                residuals = y_test - y_pred_test

                fig1 = px.histogram(
                    x=residuals,
                    nbins=30,
                    title="Распределение остатков"
                )
                st.plotly_chart(fig1, use_container_width=True)

                fig2 = px.scatter(
                    x=y_pred_test,
                    y=residuals,
                    title="Остатки vs Предсказанные значения",
                    labels={'x': 'Предсказанные значения', 'y': 'Остатки'}
                )
                fig2.add_hline(y=0, line_dash="dash", line_color="red")
                st.plotly_chart(fig2, use_container_width=True)

    # ========== ВРЕМЕННЫЕ РЯДЫ ==========
    elif analysis_method == "Анализ временных рядов":
        st.header("Анализ временных рядов")

        if 'date' not in daily_weather_df.columns:
            st.warning("Для анализа временных рядов нужна колонка с датами.")
        else:
            # Выбор города и переменной
            col1, col2 = st.columns(2)

            with col1:
                city = st.selectbox(
                    "Выберите город:",
                    daily_weather_df['city_name'].unique() if 'city_name' in daily_weather_df.columns else ['All']
                )

                if city != 'All':
                    df_city = daily_weather_df[daily_weather_df['city_name'] == city]
                else:
                    df_city = daily_weather_df

            with col2:
                variable = st.selectbox(
                    "Выберите переменную:",
                    numeric_cols.tolist()
                )

            # Агрегация по дате
            df_ts = df_city.groupby('date')[variable].mean().reset_index()
            df_ts = df_ts.sort_values('date')

            # Визуализация временного ряда
            fig = px.line(
                df_ts,
                x='date',
                y=variable,
                title=f"{variable} по времени для {city}",
                markers=True
            )
            st.plotly_chart(fig, use_container_width=True)

            # Декомпозиция временного ряда
            st.subheader("📊 Декомпозиция временного ряда")

            try:
                # Для декомпозиции нужны регулярные данные
                df_ts_regular = df_ts.set_index('date').asfreq('D')
                df_ts_regular[variable] = df_ts_regular[variable].interpolate()

                decomposition = seasonal_decompose(
                    df_ts_regular[variable],
                    model='additive',
                    period=365  # Годовая сезонность
                )

                # Графики декомпозиции
                fig_decomp = go.Figure()

                fig_decomp.add_trace(go.Scatter(
                    x=decomposition.trend.index,
                    y=decomposition.trend,
                    name='Trend',
                    line=dict(color='blue')
                ))

                fig_decomp.add_trace(go.Scatter(
                    x=decomposition.seasonal.index,
                    y=decomposition.seasonal,
                    name='Seasonal',
                    line=dict(color='green')
                ))

                fig_decomp.add_trace(go.Scatter(
                    x=decomposition.resid.index,
                    y=decomposition.resid,
                    name='Residual',
                    line=dict(color='red')
                ))

                fig_decomp.update_layout(
                    title="Декомпозиция временного ряда",
                    xaxis_title="Дата",
                    yaxis_title="Значение"
                )

                st.plotly_chart(fig_decomp, use_container_width=True)

            except Exception as e:
                st.warning(f"Не удалось выполнить декомпозицию: {e}")

            # Автокорреляция
            st.subheader("📈 Автокорреляция")

            fig_acf, ax_acf = plt.subplots(figsize=(10, 4))
            plot_acf(df_ts[variable].dropna(), ax=ax_acf, lags=50)
            st.pyplot(fig_acf)

            fig_pacf, ax_pacf = plt.subplots(figsize=(10, 4))
            plot_pacf(df_ts[variable].dropna(), ax=ax_pacf, lags=50)
            st.pyplot(fig_pacf)

    # ========== PCA ==========
    elif analysis_method == "PCA - Анализ главных компонент":
        st.header("Анализ главных компонент (PCA)")

        # Выбор признаков для PCA
        pca_features = st.multiselect(
            "Признаки для PCA:",
            numeric_cols.tolist(),
            default=numeric_cols[:5].tolist() if len(numeric_cols) >= 5 else numeric_cols.tolist()
        )

        n_components = st.slider(
            "Количество компонент:",
            2, min(10, len(pca_features)), 3
        )

        if len(pca_features) >= 2:
            X_pca = df_norm[pca_features].dropna()

            # Применение PCA
            pca = PCA(n_components=n_components)
            X_pca_transformed = pca.fit_transform(X_pca)

            # Объясненная дисперсия
            explained_variance = pca.explained_variance_ratio_
            cumulative_variance = explained_variance.cumsum()

            # График объясненной дисперсии
            fig_var = go.Figure()

            fig_var.add_trace(go.Bar(
                x=[f"PC{i+1}" for i in range(n_components)],
                y=explained_variance,
                name='Доля дисперсии'
            ))

            fig_var.add_trace(go.Scatter(
                x=[f"PC{i+1}" for i in range(n_components)],
                y=cumulative_variance,
                name='Накопленная дисперсия',
                yaxis='y2'
            ))

            fig_var.update_layout(
                title="Объясненная дисперсия по компонентам",
                yaxis=dict(title='Доля дисперсии'),
                yaxis2=dict(
                    title='Накопленная дисперсия',
                    overlaying='y',
                    side='right'
                )
            )

            st.plotly_chart(fig_var, use_container_width=True)

            # 2D визуализация первых двух компонент
            if n_components >= 2:
                df_pca_viz = df_analysis.loc[X_pca.index].copy()
                df_pca_viz['PC1'] = X_pca_transformed[:, 0]
                df_pca_viz['PC2'] = X_pca_transformed[:, 1]

                # Добавление цвета по выбранному признаку
                color_by_pca = st.selectbox(
                    "Цветовое кодирование:",
                    ['None'] + pca_features
                )

                fig_pca = px.scatter(
                    df_pca_viz,
                    x='PC1',
                    y='PC2',
                    color=color_by_pca if color_by_pca != 'None' else None,
                    title="PCA - Первые две главные компоненты",
                    hover_data=pca_features
                )

                st.plotly_chart(fig_pca, use_container_width=True)

            # 3D визуализация (если 3+ компоненты)
            if n_components >= 3:
                df_pca_viz['PC3'] = X_pca_transformed[:, 2]

                fig_pca_3d = px.scatter_3d(
                    df_pca_viz,
                    x='PC1',
                    y='PC2',
                    z='PC3',
                    color=color_by_pca if color_by_pca != 'None' else None,
                    title="PCA - Три главные компоненты"
                )

                st.plotly_chart(fig_pca_3d, use_container_width=True)

            # Загрузки компонент
            st.subheader("📊 Нагрузки компонент")

            loadings = pd.DataFrame(
                pca.components_.T,
                columns=[f'PC{i+1}' for i in range(n_components)],
                index=pca_features
            )

            st.dataframe(loadings.style.background_gradient(cmap='coolwarm', axis=0))

            # Heatmap нагрузок
            fig_loadings = px.imshow(
                loadings,
                text_auto=True,
                aspect="auto",
                title="Матрица нагрузок компонент",
                color_continuous_scale='RdBu_r'
            )

            st.plotly_chart(fig_loadings, use_container_width=True)

# ==========================================================
# PAGE 3 — FORECASTING
# ==========================================================
elif page == "📈 Прогнозирование":
    st.title("📈 Прогнозирование погодных данных")

    if 'date' not in daily_weather_df.columns:
        st.warning("Для прогнозирования нужны временные ряды.")
    else:
        st.info("""
        **Инструмент прогнозирования** позволяет строить простые прогнозы
        погодных параметров на основе исторических данных.
        """)

        # Выбор параметров прогнозирования
        col1, col2, col3 = st.columns(3)

        with col1:
            forecast_city = st.selectbox(
                "Город:",
                daily_weather_df['city_name'].unique()
            )

        with col2:
            forecast_variable = st.selectbox(
                "Переменная для прогноза:",
                [col for col in numeric_cols.tolist() if col not in ['year', 'month', 'season']]
            )

        with col3:
            forecast_horizon = st.slider(
                "Горизонт прогноза (дней):",
                1, 90, 30
            )

        # Подготовка данных
        df_forecast = daily_weather_df[
            daily_weather_df['city_name'] == forecast_city
        ].copy()

        if len(df_forecast) > 0:
            # Агрегация по дате
            df_ts_forecast = df_forecast.groupby('date')[forecast_variable].mean().reset_index()
            df_ts_forecast = df_ts_forecast.sort_values('date')

            # Простое прогнозирование (скользящее среднее)
            st.subheader("Прогноз на основе скользящего среднего")

            # Параметры скользящего среднего
            window_size = st.slider(
                "Размер окна для скользящего среднего:",
                3, 30, 7
            )

            # Расчет скользящего среднего
            df_ts_forecast['moving_avg'] = df_ts_forecast[forecast_variable].rolling(
                window=window_size,
                center=True
            ).mean()

            # Экстраполяция (простая линейная)
            last_values = df_ts_forecast[forecast_variable].tail(window_size)
            if len(last_values) >= 2:
                # Простая линейная экстраполяция
                x = np.arange(len(last_values))
                y = last_values.values
                coef = np.polyfit(x, y, 1)

                # Генерация дат для прогноза
                last_date = df_ts_forecast['date'].max()
                forecast_dates = pd.date_range(
                    start=last_date + timedelta(days=1),
                    periods=forecast_horizon,
                    freq='D'
                )

                # Прогнозные значения
                forecast_values = np.polyval(coef, np.arange(
                    len(last_values),
                    len(last_values) + forecast_horizon
                ))

                # Создание DataFrame с прогнозом
                df_forecast_future = pd.DataFrame({
                    'date': forecast_dates,
                    forecast_variable: forecast_values,
                    'type': 'Прогноз'
                })

                df_ts_forecast['type'] = 'Исторические данные'

                # Объединение исторических данных и прогноза
                df_combined = pd.concat([
                    df_ts_forecast[['date', forecast_variable, 'type']].rename(
                        columns={forecast_variable: 'value'}
                    ),
                    df_forecast_future[['date', forecast_variable, 'type']].rename(
                        columns={forecast_variable: 'value'}
                    )
                ])

                # Визуализация
                fig_forecast = px.line(
                    df_combined,
                    x='date',
                    y='value',
                    color='type',
                    title=f"Прогноз {forecast_variable} для {forecast_city}",
                    markers=True
                )

                # Добавление доверительного интервала
                historical_std = df_ts_forecast[forecast_variable].std()

                fig_forecast.add_trace(go.Scatter(
                    x=pd.concat([forecast_dates, forecast_dates[::-1]]),
                    y=pd.concat([
                        forecast_values + historical_std,
                        (forecast_values - historical_std)[::-1]
                    ]),
                    fill='toself',
                    fillcolor='rgba(255, 0, 0, 0.2)',
                    line=dict(color='rgba(255, 255, 255, 0)'),
                    name='Доверительный интервал'
                ))

                st.plotly_chart(fig_forecast, use_container_width=True)

                # Статистика прогноза
                st.subheader("📊 Статистика прогноза")

                col1, col2, col3, col4 = st.columns(4)
                with col1:
                    st.metric(
                        "Среднее значение прогноза",
                        f"{forecast_values.mean():.2f}"
                    )
                with col2:
                    st.metric(
                        "Минимальное значение",
                        f"{forecast_values.min():.2f}"
                    )
                with col3:
                    st.metric(
                        "Максимальное значение",
                        f"{forecast_values.max():.2f}"
                    )
                with col4:
                    st.metric(
                        "Тренд",
                        "📈 Восходящий" if coef[0] > 0 else "📉 Нисходящий" if coef[0] < 0 else "➡️ Стабильный"
                    )

                # Скачивание прогноза
                st.download_button(
                    label="📥 Скачать прогноз",
                    data=df_forecast_future.to_csv(index=False).encode('utf-8'),
                    file_name=f"forecast_{forecast_city}_{forecast_variable}.csv",
                    mime="text/csv"
                )

# ==========================================================
# PAGE 4 — ABOUT
# ==========================================================
else:
    st.title("ℹ️ О проекте")

    st.markdown("""
    ## Weather Analytics Dashboard

    ### 📊 Описание
    Интерактивный дашборд для анализа глобальных ежедневных погодных данных.

    ### 🔧 Функционал
    1. **Визуализация данных** - Исследование распределений, корреляций и географических данных
    2. **Анализ** - Кластеризация, регрессия, анализ временных рядов, PCA
    3. **Прогнозирование** - Простые прогнозы погодных параметров

    ### 📁 Датасеты
    - **Daily Weather**: Ежедневные погодные данные по городам
    - **Cities**: Информация о городах
    - **Countries**: Информация о странах

    ### 🛠️ Технологии
    - **Streamlit** - Фреймворк для создания дашбордов
    - **Plotly** - Интерактивная визуализация
    - **Scikit-learn** - Машинное обучение
    - **Pandas** - Обработка данных
    - **Statsmodels** - Анализ временных рядов

    ### 🚀 Запуск проекта
    ```bash
    pip install -r requirements.txt
    streamlit run app.py
    ```

    ### 📄 Структура проекта
    ```
    weather-dashboard/
    ├── app.py              # Основное приложение
    ├── requirements.txt    # Зависимости
    ├── countries.csv      # Данные по странам
    ├── cities.csv         # Данные по городам
    └── daily_weather_smallest.csv  # Ежедневные погодные данные
    ```

    ### 👨‍💻 Разработчик
    Аналитик данных / Data Scientist

    ### 📧 Контакты
    Для вопросов и предложений: ваш-email@example.com
    """)

# ==========================================================
# FOOTER
# ==========================================================
st.markdown("---")
col1, col2, col3 = st.columns(3)
with col1:
    st.caption("🌤️ Weather Analytics Dashboard")
with col2:
    st.caption(f"Данные обновлены: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
with col3:
    st.caption("© 2024 Все права защищены")
